[package]
name = "komorebi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1
